/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   argument_type_code.c                               :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: okoponen <okoponen@student.hive.fi>        +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/12/20 13:30:47 by okoponen          #+#    #+#             */
/*   Updated: 2022/12/20 13:30:53 by okoponen         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../includes/asm.h"

/*
	Generate argument type code in binary and convert it into an integer value.
	ATC is generated by looping through argument types and adding the 
	corresponding binary values into a string.
*/
void	save_atc(t_input *data)
{
	char	*atc_bi;
	int		i;

	i = 0;
	atc_bi = (char *)malloc(sizeof(char) * 9);
	if (!atc_bi)
		exit (1); //change to error
	atc_bi[8] = '\0';
	while (i <= 3)
	{
		if (data->arg_type[i] == T_REG)
			atc_bi = ft_strjoin(atc_bi, "01");
		if (data->arg_type[i] == T_DIR)
			atc_bi = ft_strjoin(atc_bi, "10");
		if (data->arg_type[i] == T_IND)
			atc_bi = ft_strjoin(atc_bi, "11");
		if (!data->arg_type[i])
			atc_bi = ft_strjoin(atc_bi, "00");
		i++;
	}
	data->argument_type_code = ft_btoi(atc_bi);
	free (atc_bi);
}
